apiVersion: apps/v1
kind: Deployment
metadata:
  name: saral-translation-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: saral-translation
  template:
    metadata:
      name: saral-translation-pod
      labels:
        app: saral-translation
    spec:
      containers:
        - name: saral-translation
          image: saral-translation
          imagePullPolicy: Never
          env:
            - name: X_API_KEY
              valueFrom:
                secretKeyRef:
                  name: saral-translation-secret
                  key: x-api-key
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: saral-translation-secret
                  key: secret-key
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: translation-db-creds
                  key: db-name
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: translation-db-creds
                  key: host
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: translation-db-creds
                  key: username
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: translation-db-creds
                  key: password
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: translation-db-creds
                  key: port
            - name: SUPERUSER_USERNAME
              valueFrom:
                secretKeyRef:
                  name: translation-secret
                  key: superuser-username
            - name: SUPERUSER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: translation-secret
                  key: supeuser-password


---

apiVersion: v1
kind: Service
metadata:
  name: saral-translation-service
spec:
  type: ClusterIP
  selector:
    app: saral-translation
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000



---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: saral-translation-ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
spec:
  rules:
    - host: saral-translation.com
      http:
        paths:
          - path: /?(.*)
            backend:
              serviceName: saral-translation-service
              servicePort: 8000
