apiVersion: v1
kind: Namespace
metadata:
  labels:
    app: translation
    tier: backend
  name: translation-backend
---

apiVersion: v1
kind: Secret
metadata:
  name: translation-db-creds
  namespace: translation-backend
type: Opaque
data:
  username: cG9zdGdyZXM=
  password: RGRBOXMxa3hIbTY1dnc4aQ==
  db-name: dHJhbnNsYXRpb24=
  host: MzQuMTMxLjI1NC4xNzk=
  port: NTQzMg==
---
apiVersion: v1
data:
  secret-key: Q1EhIkdObEdpLg==
  x-api-key: NDNiZDZjODljYTAwYjZkMDAwNDA1ZjVlODBhMjhmOTI1MjUwMWE3NjE3Mzg3ZDdmNzQwYTNjMjllZTQyZWZmNg==
  superuser-username: c3VwZXJhZG1pbg==
  supeuser-password: SjsjRiY/PStcaFdnYi52NW4hXDY4e1JBPlVCODs0
kind: Secret
metadata:
  name: saral-translation-secret
  namespace: translation-backend
type: Opaque

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: saral-translation-deployment
  namespace: translation-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: saral-translation
  template:
    metadata:
      name: saral-translation-pod
      labels:
        app: saral-translation
    spec:
      containers:
        - name: saral-translation
          image: saral-translation
          imagePullPolicy: Never
          env:
            - name: X_API_KEY
              valueFrom:
                secretKeyRef:
                  name: saral-translation-secret
                  key: x-api-key
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: saral-translation-secret
                  key: secret-key
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: translation-db-creds
                  key: db-name
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: translation-db-creds
                  key: host
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: translation-db-creds
                  key: username
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: translation-db-creds
                  key: password
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: translation-db-creds
                  key: port
            - name: SUPERUSER_USERNAME
              valueFrom:
                secretKeyRef:
                  name: saral-translation-secret
                  key: superuser-username
            - name: SUPERUSER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: saral-translation-secret
                  key: supeuser-password


---

apiVersion: v1
kind: Service
metadata:
  name: saral-translation-service
  namespace: translation-backend
spec:
  type: ClusterIP
  selector:
    app: saral-translation
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000



---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: saral-translation-ingress-service
  namespace: translation-backend
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
spec:
  rules:
    - host: saral-translation.com
      http:
        paths:
          - path: /?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: saral-translation-service
                port:
                  number: 8000
